export const group = [
  {
    username: "noahgroup",
    emailContact: "noshah@calpoly.edu",
    groupName: "noahsGroup",
    hourGoal: null,
    is_Admin: null,
    nameContact: "noah",
    phoneContact: "noah",
    safetyStatus: null,
    totalHours: 0,
  },
  {
    username: "NoPermissions",
    emailContact: "mckenna.a.reed@gmail.com",
    groupName: "NoPermissions",
    hourGoal: 2,
    is_Admin: false,
    nameContact: "MR",
    phoneContact: "123",
    safetyStatus: null,
    totalHours: 0,
  },
  {
    username: "ardenGroup",
    emailContact: "ardenozdere@gmail.com",
    groupName: "Arden's Group",
    hourGoal: null,
    is_Admin: true,
    nameContact: "Arden",
    phoneContact: "1",
    safetyStatus: null,
    totalHours: 0,
  },
  {
    username: "H4I",
    emailContact: "mckenna.a.reed@gmail.com",
    groupName: "H4I",
    hourGoal: 0,
    is_Admin: null,
    nameContact: "McKenna Reed",
    phoneContact: "4253875811",
    safetyStatus: false,
    totalHours: 0,
  },
  {
    username: "ardenGroup2",
    emailContact: "ardenozdere@gmail.com",
    groupName: "arden's group 2",
    hourGoal: null,
    is_Admin: null,
    nameContact: "Arden",
    phoneContact: "1",
    safetyStatus: null,
    totalHours: 0,
  },
  {
    username: "kennaGroup3",
    emailContact: "mckenna.a.reed@gmail.com",
    groupName: "H4I",
    hourGoal: 0,
    is_Admin: null,
    nameContact: "McKenna Reed",
    phoneContact: "4253875811",
    safetyStatus: null,
    totalHours: 0,
  },
  {
    username: "kennaGroup",
    emailContact: "mckenna.a.reed@gmail.com",
    groupName: "",
    hourGoal: 2,
    is_Admin: true,
    nameContact: "Kenna Reed",
    phoneContact: "4253875811",
    safetyStatus: null,
    totalHours: 4,
  },
];
