export const volunteers = [
  {
    username: "cblett",
    Birth_date: "1959-04-30",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "craigblett@yahoo.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Craig",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$Mwh9Tdzzx3cQ$oDZim/8y4K2cz1LEf6G6CXxRiBU2rsHtv+GqV+/ZUHc=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Blett",
    Medical_Conditions: "None",
    "Photo-Permission": "True",
    "Primary Phone": 3035034275,
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "Mica1994",
    Birth_date: "1994-06-20",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "sarmientomica77@gmail.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Micaelina",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$W6piu3Q3MuX5$zCv8Yjkxh99BCHDOPs4SkjF1kG86OKrsPxVH4KVzPHs=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Sarmiento Martinez",
    Medical_Conditions: "n/a",
    "Photo-Permission": "True",
    "Primary Phone": "760 5044425",
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "janetlang-young",
    Birth_date: "1947-04-20",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "janetlangyoung@gmail.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Janet",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$rZcBTn84NO5v$cjjT4/zz7NWSoQW+OoBPzlfOej2xIgDJnOcnTLklDBA=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Lang - Young",
    Medical_Conditions: "n/a",
    "Photo-Permission": "True",
    "Primary Phone": 8057721033,
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "kvandoorn",
    Birth_date: "2000-02-29",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "kvandoor@calpoly.edu",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Kiley",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$dGClE6reJ5c5$amZFMez9uzXPHDJop43ktI7NbQoDmEVLvCo+wj4n6Lo=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "van Doorn",
    Medical_Conditions: "N/A",
    "Photo-Permission": "True",
    "Primary Phone": 5712149544,
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "easipple",
    Birth_date: "2000-08-05",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "sipple5185@gmail.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Evan",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$XIA5MKF50CuI$Kh1ktv03itj2KY5D3SV06BUNDzNKDKEkExNsGA2MSas=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Sipple",
    Medical_Conditions: "n/a",
    "Photo-Permission": "True",
    "Primary Phone": 5627132163,
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "irishshields@gmail.com",
    Birth_date: "1946-07-30",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "irishshields@gmail.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Sue",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$JJv7I1rBQnJn$3SrDIe+MF5D2FGF723fGLLGodRyRz3/sVI15LmuOlpE=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Shields",
    Medical_Conditions: "none",
    "Photo-Permission": "True",
    "Primary Phone": 5127897763,
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "kqmckenna",
    Birth_date: "1999-09-28",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "kqmckenna123@gmail.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Kieran",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$yQ8qcmkGsjSI$2rlEC8dQLa9aC5G/CpS+piLlgocPqhVawzDlZNd2KEQ=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "McKenna",
    Medical_Conditions: "n/a",
    "Photo-Permission": "True",
    "Primary Phone": 4157555928,
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "miarolph@gmail.com",
    Birth_date: "1997-09-23",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "miarolph@gmail.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Mia",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$150000$5t7L1LBde7rc$ayBmCC2MbLukFmapnuNFzPDbBXT35uvBneUw/draRYM=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Rolph",
    Medical_Conditions: "na",
    "Photo-Permission": "True",
    "Primary Phone": 18052355928,
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "jozmina",
    Birth_date: "1960-04-15",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "jozmina@thesignplace.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Joe",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$XNpMQvAGWpJC$OkWMKgqkETfPPWUteWJ9BYEGqOxfdku2IvjK5V/l/nc=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Ozmina",
    Medical_Conditions: "None",
    "Photo-Permission": "True",
    "Primary Phone": 8059108784,
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "ko54",
    Birth_date: "1966-08-16",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "kathyoberg@gmail.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Kathy",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$jmOjJ5Huoi0T$9KS1izdyePwoKGUIbMT6UBXVN1qvIz97Q7aL2dZzCQI=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Oberg",
    Medical_Conditions: "none",
    "Photo-Permission": "True",
    "Primary Phone": "213-999-5022",
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "jjmjuan",
    Birth_date: "1982-02-22",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "jjmjuan@gmail.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Juan",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$150000$yvTejMntRWs0$qYjVHUdnpwHUAN9eC+hIc87lovbaGdD7NdC7hZd5Ca0=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Martinez",
    Medical_Conditions: "none",
    "Photo-Permission": "True",
    "Primary Phone": 7604846001,
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "chiefwmh@gmail.com",
    Birth_date: "1965-03-15",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "chiefwmh@gmail.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "William",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$150000$nOIZ4ZvHW1i4$8Oo/HpKZpezLwSXqEJmg2LsDciWHfe6Gc8+8Fo0mAuc=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Heintz",
    Medical_Conditions: "NA",
    "Photo-Permission": "True",
    "Primary Phone": 9169573883,
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "katierosemountaingoat",
    Birth_date: "2000-11-12",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "katie33rose@gmail.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Katie",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$150000$s3M6RK96xtoo$JlUudENBWaEaxuiIfevnNDxDR9IGCcM9I6PL1ENJT0M=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Rose",
    Medical_Conditions: "n/a",
    "Photo-Permission": "True",
    "Primary Phone": 8058143014,
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "rockgoalie27",
    Birth_date: "2076-11-28",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "mrblair27@gmail.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "joshua",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$150000$YIxSliqJy8oM$NIybgz465yxZQ/XgEs3xJxqvK6K2z+jI1ctv6VDN+2M=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "blair",
    Medical_Conditions: "none",
    "Photo-Permission": "True",
    "Primary Phone": 5304148179,
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "patricia.ashmun@gmail.com",
    Birth_date: "1955-09-17",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "patricia.ashmun@gmail.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Patricia",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$As5kYOVIstcA$Uc47bY3f07oAYoicopYpqw3a6DRyQsQGc3dElz09KuI=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Acheff",
    Medical_Conditions: "none",
    "Photo-Permission": "True",
    "Primary Phone": "503-320-8427",
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "Jeraddhill93",
    Birth_date: "1993-02-25",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "jeraddhill@gmail.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Jerad",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$otzgeax2gvdm$I9pod6TgskVFYV/J51+QPLuBJUowSGvLDQ8QUozkWUs=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Hill",
    Medical_Conditions: "None",
    "Photo-Permission": "True",
    "Primary Phone": 8056680124,
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "mblindt53@yahoo.com",
    Birth_date: "1953-06-29",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "mblindt53@yahoo.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Margaret",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$9HCdC2RBwLL2$l3MW17JAXtaIaDdD/gcSORIZQueycO1/CrIARdystGM=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Lindt",
    Medical_Conditions: "Bronchiectasis",
    "Photo-Permission": "True",
    "Primary Phone": "559 280-3047",
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "Joyce",
    Birth_date: "1946-02-26",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "joycerufenacht@yahoo.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Joyce",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$E8bM7MSmTKLG$x+bDFAgEXyLsKilm/krZqDMsWAh9WaBh6isHoy8ulhI=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Rufenacht",
    Medical_Conditions: "N/A",
    "Photo-Permission": "True",
    "Primary Phone": 6613316757,
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "msarno",
    Birth_date: "2000-03-18",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "morgansarno18@icloud.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Morgan",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$o3519ra1vYsA$Uofcu7cUUOUcMLggMVadCEf/Ffp6hZz2b6cOWJekL3w=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Sarno",
    Medical_Conditions: "N/A",
    "Photo-Permission": "True",
    "Primary Phone": 8185233976,
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "Pam",
    Birth_date: "1935-01-04",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "pamela.gatz@gmail.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Pamela",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$OB70xMhyzaAB$lqgbKRZQffvZm3g19a/tF1dM0t6p4vzuylzvTWT6W0I=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Gatz",
    Medical_Conditions: "none",
    "Photo-Permission": "True",
    "Primary Phone": "805-806-1109",
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "chack55",
    Birth_date: "1994-05-05",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "christinahack55@gmail.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Christy",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$EABMuohqL2Zb$w7ThJQPqFCcAA9GdOOZCMUf2Hm3d8FX3W1KtNvOn3ZY=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Hack",
    Medical_Conditions: "None",
    "Photo-Permission": "True",
    "Primary Phone": 8055910106,
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "ericnewcomer",
    Birth_date: "1998-10-23",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "enewcome@calpoly.edu",
    Emergency_Contact: "Thomas Newcomer",
    Emergency_Contact_Phone: 7147093697,
    "First Name": "Eric",
    Group: "Test Group",
    Hashed_Password:
      "pbkdf2_sha256$216000$r2pnyUm0ip4C$/eetuv89JslcC0k+zeHAeD1CpZ7psTPXzTwqFdBq2As=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Newcomer",
    Medical_Conditions: "none",
    "Photo-Permission": "True",
    "Primary Phone": 3609208314,
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "havendl",
    Birth_date: "1992-12-01",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "havendl@gmail.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Haven",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$Ida0VY60ID96$/VaT6iLP8IgcoAG2t9teYTpOkC8HtOzdXBvkt+ZaMoU=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Dlott",
    Medical_Conditions: "N/A",
    "Photo-Permission": "True",
    "Primary Phone": "(831) 332-9009",
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "mcossey",
    Birth_date: "1995-04-21",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "maiacossey@gmail.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Mariah",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$QixLCLZYaGz8$+y+YhZEWajqQ0IPwarj6fQarPI4YNr5c4YyEfqHV1oI=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Cossey",
    Medical_Conditions: "NA",
    "Photo-Permission": "True",
    "Primary Phone": "424 241-8406",
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "oceana",
    Birth_date: "1991-03-13",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "oceanayoga333@icloud.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Ana",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$wgWxjnWtHo1E$DkkxYU+lOtHAvLga5D4kCPrFp7jY6dkg7+h7SC2xPbk=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Culbertson",
    Medical_Conditions: "None",
    "Photo-Permission": "True",
    "Primary Phone": 8086403101,
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "WRG",
    Birth_date: "None",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$DLyLV8CrO82y$cvHNn/k6PyP+MRv+p89gkxcZKn0MvWqPNT4RRuFagbw=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "",
    Medical_Conditions: "",
    "Photo-Permission": "True",
    "Primary Phone": "",
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "mmele",
    Birth_date: "2000-07-04",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "mariannarosemele@gmail.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Marianna",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$Ov2bH7OifTNs$YGgX9joHG/GvW7IeZwmzpQ0MSdkiWd8aAze4rc/tbAQ=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Marianna",
    Medical_Conditions: "none",
    "Photo-Permission": "True",
    "Primary Phone": 2066174355,
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "jessicawright",
    Birth_date: "None",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$UzFp3vAMdLTE$EodEUfC0Dxi/KO1U2jq4eRKipUyFXwq3g2EezPnc7uU=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "",
    Medical_Conditions: "",
    "Photo-Permission": "True",
    "Primary Phone": "",
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "beverleysessa88@gmail.com",
    Birth_date: "1937-03-14",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "beverleysessa88@gmail.com",
    Emergency_Contact: "Katheryn Glenn",
    Emergency_Contact_Phone: "508-904-6670",
    "First Name": "Beverley",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$qWd5AUG4NkwQ$rNRWHWgB9G57JNI04e+6A87ZTZNyKUveLdkZAEWRITM=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Sessa",
    Medical_Conditions: "Afib",
    "Photo-Permission": "True",
    "Primary Phone": "805-234-0768",
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "peter@slobg.org",
    Birth_date: "1993-09-22",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "peter@slobg.org",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Peter",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$J8ukdAfxaUME$3VdW7BB/rNaLeBibd6nHCi8qqj9msZmyArx5z77fpIM=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Sarracino",
    Medical_Conditions: "n/a",
    "Photo-Permission": "True",
    "Primary Phone": 2392221369,
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "Janine",
    Birth_date: "1961-09-28",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "designsbyja9@gmail.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Janine",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$01YfTZD7OFVs$chdqyXWe/C2HsjwFKEHt8K8Ifb2rrq2kI3BvHjmkXyc=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Stillman",
    Medical_Conditions: "none",
    "Photo-Permission": "True",
    "Primary Phone": 8054597296,
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "sandraadamsb@gmail.com",
    Birth_date: "1950-01-23",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "sandraadamsb@gmail.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "SANDRA",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$BwuNPxp3s36M$teFxJZ7nu1xYJwzWIzWrM8ZjXm9YafHO77XLtc1IlpA=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "ADAMS",
    Medical_Conditions: "none",
    "Photo-Permission": "True",
    "Primary Phone": 8054390486,
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "rsaliklis",
    Birth_date: "1962-08-18",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "rsaliklis@yahoo.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Ruta",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$HUjsfKFnLN8A$FxbZUJdPCNCvN1t4Uflodt0y9DTRtejA1igb905K5YI=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Saliklis",
    Medical_Conditions: "Seasonal allergies",
    "Photo-Permission": "True",
    "Primary Phone": 8057044341,
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "lunabailey",
    Birth_date: "1997-07-01",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "lunabailey540@gmail.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Luna",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$6OhSVo6X5aoD$vQHI4YfPTQ8/HtCr8fBjIVKYSs321VKrAyyhRXjp+iE=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Bailey",
    Medical_Conditions: "None",
    "Photo-Permission": "True",
    "Primary Phone": 8055408728,
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "JadeLT",
    Birth_date: "2002-01-21",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "jadetaylor0121@gmail.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Jade",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$CGv7PZEOuydo$m53Y6B3bwymP3jZ3dmNfA5Grf+TXg8w5khAnkANRrfY=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Taylor",
    Medical_Conditions: "none",
    "Photo-Permission": "True",
    "Primary Phone": "(530)219-4603",
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "stonersauto@gmail.com",
    Birth_date: "1952-05-20",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "stonersauto@gmail.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Gary",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$KaR5Dx6Mfxff$S3+4tWWtTwWvl4FK6UUPQrcpd7DJw40mVcsc13trGfw=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Stoner",
    Medical_Conditions: "Legally Blind",
    "Photo-Permission": "True",
    "Primary Phone": 8052354184,
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "Harryharlow58",
    Birth_date: "1948-05-22",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "harryharlow229@gmail.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Harry",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$1w5nDu9OXb9z$gQfO12hllxhR6dSbRrH/jbzGHyqI/n7Ze+hVYMLzt2I=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Harlow",
    Medical_Conditions: "None",
    "Photo-Permission": "True",
    "Primary Phone": "805 234-2778",
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "AlyssaThomas",
    Birth_date: "1996-09-15",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "alyhthomas@gmail.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Alyssa",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$150000$kucUnRWaPTl1$S+ShE6v8AWnlqUPfylxi4V41ZoTHDyJnfA5+ofrpFII=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Thomas",
    Medical_Conditions: "Bee allergies\nPeanut allergies \nAsthma",
    "Photo-Permission": "True",
    "Primary Phone": 8052150424,
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "SkyeSeher1",
    Birth_date: "2003-02-14",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "skyeseher@icloud.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Skye",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$k2ekBYucpOL0$TB7oYi932aj2QZ9smMRANMdoSQ3GTDe7tvGnGR9gats=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Seher",
    Medical_Conditions: "None",
    "Photo-Permission": "True",
    "Primary Phone": 8054310244,
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "cschwaegerle",
    Birth_date: "1995-07-17",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "camille.schwaegerle@gmail.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Camille",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$Yttg6ORfdj5j$u5UHcWrQriZBRp5gGE+YPIub9eVLX5A+wGBVqHPLODQ=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Schwaegerle",
    Medical_Conditions: "N/A",
    "Photo-Permission": "True",
    "Primary Phone": 8052155073,
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "wendyamckeown",
    Birth_date: "1956-01-10",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "wendyamckeown@gmail.com",
    Emergency_Contact: "John Mottmann",
    Emergency_Contact_Phone: "(805)470-8275",
    "First Name": "Wendy A",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$150000$R7KwluuxiJG1$C+bHsz+EEko+ZTSTk5lg5wRAaMPmsoUo5i02z+u5ME4=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "McKeown",
    Medical_Conditions: "hypothyroidism (treated)",
    "Photo-Permission": "True",
    "Primary Phone": 8055501838,
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "jdomine",
    Birth_date: "1993-08-28",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "jmdomine10@gmail.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Jacob",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$V1Ax6h1280ep$/hKgvTNPaXLttO9JXyTICGhXjzaLAHRYp8Jfssvb+6A=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Domine",
    Medical_Conditions: "None",
    "Photo-Permission": "True",
    "Primary Phone": 8184212713,
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "Oreeves",
    Birth_date: "2000-03-25",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "oliviagrace325@gmail.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Olivia",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$MQSYB4FbERGB$StUaMSwqCwUMiXA6yoXUlibR9Zg+tJl+OHoZNwyvERI=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Reeves",
    Medical_Conditions: "None",
    "Photo-Permission": "True",
    "Primary Phone": "(916)945-0926",
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "alevine",
    Birth_date: "1996-03-12",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "annamaelevine@gmail.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Anna",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$YTD99jt4p0dH$s6sojmrzDLJq7SOvlYgT8fDJZrwQWr1ItU13tvGtZHw=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Levine",
    Medical_Conditions: "peanuts, advil",
    "Photo-Permission": "True",
    "Primary Phone": 4089816861,
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "carmacknaomi22",
    Birth_date: "2004-05-10",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "carmacknaomi@gmail.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Naomi",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$evp2JAZmJSNZ$Y+EKAb7QuYxlgZb8ukt3j+COwQemnPO2CiCZlGslJbA=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Carmack",
    Medical_Conditions: "none",
    "Photo-Permission": "True",
    "Primary Phone": 8054649367,
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "jouyang",
    Birth_date: "1999-02-06",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "jouyang@calpoly.edu",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Jessica",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$llGFWznzuhB0$WSNy0kEpDivhFHCn9RmVX58Z9c/rxVodx6kXfkxJJZM=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Ouyang",
    Medical_Conditions: "None",
    "Photo-Permission": "True",
    "Primary Phone": 4156808357,
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "jwfarley",
    Birth_date: "1981-01-07",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "jwfarleyssg@yahoo.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Joshua",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$150000$G8xk25ubi76b$jICWX/hXIMvd+qguaYLxQ1nWwy+KkTY7oiaV0CV+aNk=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Farley",
    Medical_Conditions: "None",
    "Photo-Permission": "True",
    "Primary Phone": 6613197150,
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "kmramsey",
    Birth_date: "1999-03-05",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "Kristinaramsey7@gmail.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Kristina",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$sMgA7XGCJN86$XnlLrmAsQUab7ZyC2VqcOINyD/io00J977ziI55/+nA=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Ramsey",
    Medical_Conditions: "none",
    "Photo-Permission": "True",
    "Primary Phone": "805-556-5586",
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "elaineneselun",
    Birth_date: "1992-10-11",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "elaine.eselun@gmail.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Elaine",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$nEbVd1HTRLsv$+l0sk77pFwRzr1PU4bziwBTMA3TAKGJQuqZhR+TR0LU=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Eselun",
    Medical_Conditions: "3940-7 Broad Street, San Luis Obispo, CA 93101",
    "Photo-Permission": "True",
    "Primary Phone": 8057488566,
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
  {
    username: "Ajsabin",
    Birth_date: "2000-10-09",
    "Community Service": "False",
    Covid_Waiver_and_Release: "True",
    Email: "amandajsabin@gmail.com",
    Emergency_Contact: "",
    Emergency_Contact_Phone: "",
    "First Name": "Amanda",
    Group: "",
    Hashed_Password:
      "pbkdf2_sha256$216000$7fKpZbPJAfmT$ttpa6kdFaTLfwb5FKIqtCcjduyozdM53BBp7F+ILjlU=",
    "Hour Goal": "Not Specified",
    is_Admin: "False",
    "Last Name": "Sabin",
    Medical_Conditions: "N/A",
    "Photo-Permission": "True",
    "Primary Phone": 8582280389,
    "Safety Training Status": "True",
    "Secondary Phone": "N/A",
    "Total Hours Volunteered": 0,
    Volunter_Waiver_and_Release: "True",
  },
];
